---
# tasks file for myapache

- name: "Install httpd"
  package:
          name: "httpd"
          state: present

- name: "Installing php"
  package:
          name: php
          state: present

- name: "copy web pages"
  copy:
          src: /root/load/index.php
          dest: /var/www/html

- name: "starting service"
  service:
          name: httpd
          state: started
